drop database if exists insurance;
create database if not exists insurance;

use insurance;

CREATE TABLE IF NOT EXISTS  CUSTOMER (
   CUST_ID INT NOT NULL,
   CUST_FNAME VARCHAR(45) ,
   CUST_LNAME VARCHAR(45),
   CUST_DOB DATE,
   CUST_GENDER ENUM("M", "F"),
   CUST_ADDRESS VARCHAR(45),
   CUST_EMAIL VARCHAR(45),
   CUST_MOB_NUMBER INT,
   CUST_PASSPORT_NUMBER VARCHAR(45),
   CUST_MARITAL_STATUS VARCHAR(45),
   CUST_PPS_NUMBER INT,
  PRIMARY KEY ( CUST_ID)
  );

CREATE TABLE IF NOT EXISTS  MEMBERSHIP (
   MEMBERSHIP_ID INT NOT NULL,
   MEMBERSHIP_TYPE VARCHAR(45),
   ORGANISATION_CONTACT INT,
  PRIMARY KEY ( MEMBERSHIP_ID)
  );

CREATE TABLE IF NOT EXISTS  PREMIUM (
   PREMIUM_PAYMENT_ID INT NOT NULL,
   CUST_ID INT,
   POLICY_NUMBER INT ,
   PREMIUM_PAYMENT_SCHEDULE DATE,
   PREMIUM_PAYMENT_AMOUNT INT,
  PRIMARY KEY ( PREMIUM_PAYMENT_ID),
  FOREIGN KEY ( CUST_ID)
  REFERENCES  CUSTOMER ( CUST_ID)
  );

CREATE TABLE IF NOT EXISTS  CLAIM (
   CLAIM_ID INT NOT NULL,
   CUST_ID INT,
   CLAIM_AMOUNT INT,
   INCIDENT_ID INT,
   DAMAGE_TYPE VARCHAR(45),
   DATE_OF_CLAIM DATE,
   CLAIM_STATUS VARCHAR(45),
  PRIMARY KEY ( CLAIM_ID),
  FOREIGN KEY ( CUST_ID)
  REFERENCES  CUSTOMER ( CUST_ID)
  );

CREATE TABLE IF NOT EXISTS  VEHICLE (
   VEHICLE_ID INT NOT NULL,
   CUST_ID INT,
   POLICY_ID INT,
   DEPENDENT_NOK_ID INT,
   VEHICLE_REGISTRATION_NUMBER INT,
   VEHICLE_VALUE INT,
   VEHICLE_TYPE VARCHAR(45),
   VEHICLE_SIZE INT,
   VEHICLE_NUMBER_OF_SEAT INT,
   VEHICLE_MANUFACTURER VARCHAR(45),
   VEHICLE_ENGINE_NUMBER VARCHAR(45),
   VEHICLE_CHASIS_NUMBER VARCHAR(45),
   VEHICLE_NUMBER VARCHAR(45),
   VEHICLE_MODEL_NUMBER VARCHAR(45),
  PRIMARY KEY ( VEHICLE_ID),
    FOREIGN KEY ( CUST_ID)
    REFERENCES  CUSTOMER ( CUST_ID)
	);

CREATE TABLE IF NOT EXISTS  SETTLEMENT (
   CLAIM_SETTLEMENT_ID INT NOT NULL,
   CLAIM_ID INT,
   DATE_SETTLED DATE,
   AMOUNT_PAID INT,
  PRIMARY KEY ( CLAIM_SETTLEMENT_ID),
  FOREIGN KEY ( CLAIM_ID)
  REFERENCES  CLAIM ( CLAIM_ID)
    );

CREATE TABLE IF NOT EXISTS  STAFF (
   STAFF_ID INT NOT NULL,
   STAFF_FNAME VARCHAR(45),
   STAFF_LNAME VARCHAR(45),
   STAFF_ADDRESS VARCHAR(45),
   STAFF_CONTACT INT,
   STAFF_GENDER ENUM("M","F"),
   STAFF_NATIONALITY VARCHAR(45),
   STAFF_QUALIFICATION VARCHAR(45),
   STAFF_ALLOWANCE INT,
   STAFF_PPS_NUMBER INT,
   STAFF_MARITAL_STATUS VARCHAR(45),
  PRIMARY KEY ( STAFF_ID)
  );

CREATE TABLE IF NOT EXISTS  APPLICATION (
   APPLICATION_ID INT NOT NULL,
   CUST_ID INT,
   VEHICLE_ID INT,
   COVERAGE VARCHAR(80),
  PRIMARY KEY ( APPLICATION_ID),
  FOREIGN KEY ( CUST_ID)
  REFERENCES  CUSTOMER ( CUST_ID)
  );

CREATE TABLE IF NOT EXISTS  INSURANCE_POLICY (
   AGREEMENT_ID INT NOT NULL,
   APPLICATION_ID INT,
   POLICY_NUMBER INT,
   START_DATE DATE,
   EXPIRY_DATE DATE,
   TERM_CONDITION_DESCRIPTION VARCHAR(500),
  PRIMARY KEY ( AGREEMENT_ID),
  FOREIGN KEY ( APPLICATION_ID)
  REFERENCES  APPLICATION ( APPLICATION_ID)
  );

CREATE TABLE IF NOT EXISTS  INSURANCE_POLICY_COVERAGE (
   IPC_ID INT NOT NULL,
   AGREEMENT_ID INT,
   IPC_CLAIM_DATE DATE,
   IPC_CLAIM_REASON VARCHAR(200),
  PRIMARY KEY ( IPC_ID),
  FOREIGN KEY ( AGREEMENT_ID)
  REFERENCES  INSURANCE_POLICY ( AGREEMENT_ID)
  );

CREATE TABLE IF NOT EXISTS  DEPARTMENT (
   DEPARTMENT_NAME VARCHAR(20) NOT NULL,
   IPC_ID INT,
   CONTACT_INFORMATION VARCHAR(45),
   DEPARTMENT_STAFF VARCHAR(45),
   DEPARTMENT_LEADER VARCHAR(45),
  PRIMARY KEY ( DEPARTMENT_NAME),
  FOREIGN KEY ( IPC_ID)
  REFERENCES  INSURANCE_POLICY_COVERAGE ( IPC_ID)
  );

CREATE TABLE IF NOT EXISTS  OFFICE (
   OFFICE_NAME VARCHAR(20) NOT NULL,
   OFFICE_LEADER VARCHAR(45),
   CONTACT_INFORMATION VARCHAR(45),
   ADDRESS VARCHAR(45),
   ADMIN_COST INT,
   STAFF VARCHAR(45),
  PRIMARY KEY ( OFFICE_NAME)
  );

CREATE TABLE IF NOT EXISTS  SERVICE (
   VEHICLE_SERVICE VARCHAR(20) NOT NULL,
   IPC_ID INT,
   VEHICLE_SERVICE_ADDRESS VARCHAR(200),
   VEHICLE_SERVICE_CONTACT INT,
   VEHICLE_SERVICE_INCHARGE VARCHAR(45),
   VEHICLE_SERVICE_TYPE VARCHAR(45),
  PRIMARY KEY ( VEHICLE_SERVICE),
  FOREIGN KEY ( IPC_ID)
  REFERENCES  INSURANCE_POLICY_COVERAGE ( IPC_ID)
  );

CREATE TABLE IF NOT EXISTS  NOK (
   NOK_ID INT NOT NULL,
   AGREEMENT_ID INT,
   NOK_NAME VARCHAR(45),
   NOK_ADDRESS VARCHAR(45),
   NOK_PHONE_NUMBER INT,
   NOK_MARITAL_STATUS VARCHAR(45),
   NOK_GENDER ENUM("M", "F"),
  PRIMARY KEY ( NOK_ID),
  FOREIGN KEY ( AGREEMENT_ID)
  REFERENCES  INSURANCE_POLICY ( AGREEMENT_ID)
  );

CREATE TABLE IF NOT EXISTS  COMPANY (
   COMPANY_NAME VARCHAR(20) NOT NULL,
   COMPANY_ADDRESS VARCHAR(45),
   COMPANY_CONTACT_NUMBER INT,
   COMPANY_FAX INT,
   COMPANY_EMAIL VARCHAR(45),
   COMPANY_WEBSITE VARCHAR(45),
   COMPANY_LOCATION VARCHAR(45),
   COMPANY_DEPARTMENT_NAME VARCHAR(45),
   COMPANY_OFFICE_NAME VARCHAR(45),
   DEPARTMENT_NAME VARCHAR(45),
  PRIMARY KEY ( COMPANY_NAME),
  FOREIGN KEY ( DEPARTMENT_NAME)
  REFERENCES  DEPARTMENT ( DEPARTMENT_NAME)
  );

CREATE TABLE IF NOT EXISTS  TERMS_CONDITIONS (
   COVERAGE_ID INT NOT NULL,
   COVERAGE_AMOUNT INT,
   COVERAGE_TYPE VARCHAR(45),
   COVERAGE_LEVEL VARCHAR(45),
   PRODUCT_ID VARCHAR(45),
   COVERAGE_DESCRIPTION VARCHAR(45),
   COVERAGE_TERMS VARCHAR(45),
  PRIMARY KEY ( COVERAGE_ID)
  );

CREATE TABLE IF NOT EXISTS  RECEIPT (
   RECEIPT_ID INT NOT NULL,
   PREMIUM_PAYMENT_ID INT,
   COST INT,
   TIME DATE,
  PRIMARY KEY ( RECEIPT_ID),
  FOREIGN KEY ( PREMIUM_PAYMENT_ID)
  REFERENCES  PREMIUM ( PREMIUM_PAYMENT_ID)
  );

CREATE TABLE IF NOT EXISTS  QUOTE (
   QUOTE_ID INT NOT NULL,
   APPLICATION_ID INT,
   ISSUE_DATE DATE,
   VALID_FROM_DATE DATE,
   VALID_TILL_DATE DATE,
   DESCRIPTION VARCHAR(45),
   PRODUCT_ID VARCHAR(45),
   COVERAGE_LEVEL VARCHAR(45),
  PRIMARY KEY ( QUOTE_ID),
  FOREIGN KEY ( APPLICATION_ID)
  REFERENCES  APPLICATION ( APPLICATION_ID)
  );

CREATE TABLE IF NOT EXISTS  CUSTOMER_MEMBERSHIP (
   CUST_ID INT NOT NULL,
   MEMBERSHIP_ID INT NOT NULL,
  PRIMARY KEY ( CUST_ID,  MEMBERSHIP_ID),
  FOREIGN KEY ( CUST_ID)
  REFERENCES  CUSTOMER ( CUST_ID),
  FOREIGN KEY ( MEMBERSHIP_ID)
  REFERENCES  MEMBERSHIP ( MEMBERSHIP_ID)
  );

CREATE TABLE IF NOT EXISTS  DEPARTMENT_OFFICE (
   DEPARTMENT_NAME VARCHAR(20) NOT NULL,
   OFFICE_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY ( DEPARTMENT_NAME,  OFFICE_NAME),
  FOREIGN KEY ( DEPARTMENT_NAME)
  REFERENCES  DEPARTMENT ( DEPARTMENT_NAME),
  FOREIGN KEY ( OFFICE_NAME)
  REFERENCES  OFFICE ( OFFICE_NAME)
  );

CREATE TABLE IF NOT EXISTS  COMPANY_STAFF (
   COMPANY_NAME VARCHAR(20) NOT NULL,
   STAFF_ID INT NOT NULL,
  PRIMARY KEY ( COMPANY_NAME,  STAFF_ID),
  FOREIGN KEY ( COMPANY_NAME)
  REFERENCES  COMPANY ( COMPANY_NAME),
  FOREIGN KEY ( STAFF_ID)
  REFERENCES  STAFF ( STAFF_ID)
  );

CREATE TABLE IF NOT EXISTS  INSURANCE_POLICY_TERMS_CONDITIONS (
   AGREEMENT_ID INT NOT NULL,
   COVERAGE_ID INT NOT NULL,
  PRIMARY KEY ( AGREEMENT_ID,  COVERAGE_ID),
  FOREIGN KEY ( AGREEMENT_ID)
  REFERENCES  INSURANCE_POLICY ( AGREEMENT_ID),
  FOREIGN KEY ( COVERAGE_ID)
  REFERENCES  TERMS_CONDITIONS ( COVERAGE_ID)
  );